version: '3.5'
services:
  smooch-jwt:
    build:
      context: .
      cache_from:
        - gcr.io/zip-zap-gateway/smooch-jwt
      args:
        - CODECOV_TOKEN=$CODECOV_TOKEN
    image: gcr.io/zip-zap-gateway/smooch-jwt
    ports:
      - '8080:8080'
    environment:
        - SECRET=$SECRET
        - KEY_ID=$KEY_ID
    command: npm start